
export const FETCH_ALL= 'FETCH_ALL';
export const FETCH_REPORT='FETCH_REPORT'
export const AUTH='AUTH';
export const LOGOUT='LOGOUT';
export const SERVER_ERROR="SERVER_ERROR";
export const FETCH_ALL_OPTION_FOR_DROPDOWN="FETCH_ALL_OPTION_FOR_DROPDOWN"
